### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by Jaimer117** [SistemasTecTlaxiaco/infografia-Jaimer117#1]
![Infografia de Realidad Aumentada](https://user-images.githubusercontent.com/80010898/153766860-d5889fe1-4bb5-463d-adac-9dd6d319de70.png)

**Comment by Christopherg2** [comment]
Muy bien compañero tu trabajo esta completo, y cumple con todos los requisitos. 
20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
